# Generated by Django 2.2.8 on 2020-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(unique=True),
        ),
    ]
