# Generated by Django 2.2.8 on 2020-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0004_auto_20200727_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='urlkey',
            field=models.CharField(default='https://google.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(unique=True),
        ),
    ]
