# Generated by Django 2.2.8 on 2020-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0005_auto_20200727_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urlkey',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
