# Generated by Django 2.2.8 on 2020-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0006_auto_20200727_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.URLField(),
        ),
    ]
