# Generated by Django 2.2.8 on 2020-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0007_auto_20200727_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urlkey',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
